"""
NIFTY Options Data Downloader

This script downloads NIFTY options data with the following logic:
1. Loads NIFTY spot prices from nifty_spot_prices.json file (generated by download_nifty_spot_dhan.py)
2. For each day:
   - Uses spot price from file to calculate 20 strikes above and 20 below
   - Finds the expiry date (nearest expiry day, configurable via EXPIRY_DAY in .env)
   - Downloads 1-minute data for both CALL and PUT options
   - Marks days with no data as holidays

3. Data is saved in separate files per date: nifty_options_YYYY-MM-DD.json

Configuration via .env file:
- START_DATE: Start date (YYYY-MM-DD)
- END_DATE: End date (YYYY-MM-DD)
- EXPIRY_DAY: Expiry weekday (0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday)
"""

import os
import json
import time
from datetime import datetime, timedelta
from dotenv import load_dotenv
from breeze_connect import BreezeConnect
from collections import defaultdict

# Load environment variables
load_dotenv()

# Data/output configuration
DATA_DIR = "data"
OPTIONS_DIR = os.path.join(DATA_DIR, "options")
os.makedirs(OPTIONS_DIR, exist_ok=True)

# Get credentials from environment variables
api_key = os.getenv('ICICI_API_KEY')
api_secret = os.getenv('ICICI_SECRET_KEY')
session_token = os.getenv('ICICI_SESSION_TOKEN')

if not api_key or not api_secret or not session_token:
    raise ValueError("ICICI_API_KEY, ICICI_SECRET_KEY, and ICICI_SESSION_TOKEN must be set in .env file")

# Initialize SDK
print("Initializing BreezeConnect...")
breeze = BreezeConnect(api_key=api_key)

# Generate Session
print("Generating session...")
breeze.generate_session(api_secret=api_secret, session_token=session_token)

def load_spot_prices_from_file(file_path=os.path.join(DATA_DIR, 'nifty_spot_prices.json')):
    """Load NIFTY spot prices from JSON file"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        spot_prices = data.get('spot_prices', {})
        date_range = data.get('date_range', {})
        
        if not spot_prices:
            raise ValueError(f"No spot prices found in {file_path}")
        
        print(f"✓ Loaded {len(spot_prices)} spot price records from {file_path}")
        if date_range:
            print(f"  Date range in file: {date_range.get('start')} to {date_range.get('end')}")
        
        return spot_prices
    except FileNotFoundError:
        raise FileNotFoundError(f"Spot prices file not found: {file_path}. Please run download_nifty_spot_dhan.py first.")
    except json.JSONDecodeError as e:
        raise ValueError(f"Error parsing {file_path}: {e}")

def find_nearest_expiry_day(date, expiry_weekday):
    """Find the nearest expiry day for a given date"""
    # expiry_weekday: 0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday
    # The expiry date must be >= trading date (can't use expired contracts)
    # Always use the next expiry day (or same day if it's the expiry day)
    
    if date.weekday() == expiry_weekday:  # It's the expiry day - use this day as expiry
        return date
    
    # Calculate days until next expiry day
    days_ahead = expiry_weekday - date.weekday()
    if days_ahead <= 0:  # Target day already happened this week
        days_ahead += 7
    
    next_expiry = date + timedelta(days=days_ahead)
    return next_expiry

def find_next_expiry_day(date, expiry_weekday):
    """Find the next expiry day after the given date (7 days later if date is expiry day)"""
    # If date is the expiry day, return the expiry day 7 days later
    if date.weekday() == expiry_weekday:
        return date + timedelta(days=7)
    
    # Otherwise, find the next expiry day, then add 7 more days
    days_ahead = expiry_weekday - date.weekday()
    if days_ahead <= 0:  # Target day already happened this week
        days_ahead += 7
    # Add 7 more days to get the expiry day after the current one
    days_ahead += 7
    
    return date + timedelta(days=days_ahead)

def find_previous_day(expiry_date, expiry_weekday):
    """Find the day before a given expiry date (fallback expiry)"""
    if expiry_date.weekday() == expiry_weekday:
        return expiry_date - timedelta(days=1)  # Return previous day
    return expiry_date

def calculate_strikes(spot_price, num_strikes=20):
    """Calculate strike prices (20 above and 20 below spot)"""
    # NIFTY strikes are typically in multiples of 50
    strike_interval = 50
    
    # Round spot to nearest strike
    base_strike = round(spot_price / strike_interval) * strike_interval
    
    strikes = []
    # 20 strikes below
    for i in range(num_strikes, 0, -1):
        strikes.append(int(base_strike - (i * strike_interval)))
    # Spot strike (or nearest)
    strikes.append(int(base_strike))
    # 20 strikes above
    for i in range(1, num_strikes + 1):
        strikes.append(int(base_strike + (i * strike_interval)))
    
    return strikes

def download_options_data(breeze, date_str, expiry_date_str, strike_price, right_type):
    """Download 1-minute historical data for a specific option"""
    try:
        from_time = f"{date_str}T09:15:00.000Z"
        to_time = f"{date_str}T15:30:00.000Z"
        
        data = breeze.get_historical_data_v2(
            stock_code="NIFTY",
            exchange_code="NFO",
            from_date=from_time,
            to_date=to_time,
            interval="1minute",
            product_type="options",
            expiry_date=expiry_date_str,
            right=right_type,
            strike_price=str(strike_price)
        )
        
        # Rate limiting - be respectful
        time.sleep(0.1)  # Small delay between requests
        
        if isinstance(data, dict) and data.get('Status') == 200:
            success = data.get('Success', [])
            if success and len(success) > 0:
                return success
        return []
    except Exception as e:
        print(f"    Error downloading {right_type} {strike_price}: {e}")
        return []

def check_expiry_has_data(breeze, date_str, expiry_date_iso, sample_strike):
    """Check if an expiry date has data available by trying a sample strike"""
    # Try downloading one strike to check if expiry has data
    test_data = download_options_data(breeze, date_str, expiry_date_iso, sample_strike, 'call')
    return len(test_data) > 0

def save_daily_data(date_str, day_data, spot_price, expiry_date_str):
    """Save data for a single day to a separate file"""
    output_file = os.path.join(OPTIONS_DIR, f"nifty_options_{date_str}.json")
    
    output_data = {
        'date': date_str,
        'spot_price': spot_price,
        'expiry_date': expiry_date_str,
        'data': day_data
    }
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, indent=2, ensure_ascii=False)
    
    return output_file

def save_next_expiry_data(date_str, day_data, spot_price, expiry_date_str):
    """Save next expiry data to a separate file with _next_expiry suffix"""
    output_file = os.path.join(OPTIONS_DIR, f"nifty_options_{date_str}_next_expiry.json")
    
    output_data = {
        'date': date_str,
        'spot_price': spot_price,
        'expiry_date': expiry_date_str,
        'data': day_data
    }
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, indent=2, ensure_ascii=False)
    
    return output_file

def main():
    # Read date range and expiry day from environment variables
    start_date_str = os.getenv('START_DATE')
    end_date_str = os.getenv('END_DATE')
    expiry_day_str = os.getenv('EXPIRY_DAY')
    
    if not start_date_str or not end_date_str:
        raise ValueError("START_DATE and END_DATE must be set in .env file (format: YYYY-MM-DD)")
    
    if not expiry_day_str:
        raise ValueError("EXPIRY_DAY must be set in .env file (0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday)")
    
    # Parse dates
    try:
        start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
        end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
    except ValueError as e:
        raise ValueError(f"Invalid date format in .env. Use YYYY-MM-DD format. Error: {e}")
    
    # Parse expiry day
    try:
        expiry_weekday = int(expiry_day_str)
        if expiry_weekday < 0 or expiry_weekday > 6:
            raise ValueError("EXPIRY_DAY must be between 0 (Monday) and 6 (Sunday)")
    except ValueError as e:
        raise ValueError(f"Invalid EXPIRY_DAY in .env. Must be 0-6. Error: {e}")
    
    weekday_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    print(f"Expiry day: {weekday_names[expiry_weekday]} ({expiry_weekday})")
    
    print(f"Downloading NIFTY options data from {start_date.date()} to {end_date.date()}")
    print("=" * 80)
    
    # Step 1: Load NIFTY spot prices from existing file
    print(f"\n{'='*80}")
    print("Step 1: Loading NIFTY spot prices from file...")
    print(f"{'='*80}\n")
    
    # Load spot prices from data/nifty_spot_prices.json (default path)
    spot_prices = load_spot_prices_from_file()
    
    if not spot_prices:
        print("✗ Failed to load spot prices. Exiting.")
        return
    
    # Verify date range coverage
    sorted_dates = sorted(spot_prices.keys())
    file_start = sorted_dates[0]
    file_end = sorted_dates[-1]
    
    if file_start > start_date.strftime("%Y-%m-%d"):
        print(f"⚠ Warning: Spot prices file starts from {file_start}, but requested start date is {start_date.strftime('%Y-%m-%d')}")
    if file_end < end_date.strftime("%Y-%m-%d"):
        print(f"⚠ Warning: Spot prices file ends at {file_end}, but requested end date is {end_date.strftime('%Y-%m-%d')}")
    
    print(f"\n{'='*80}")
    print("Step 2: Downloading options data for each day...")
    print(f"{'='*80}")
    print("Step 2: Downloading options data for each day...")
    print(f"{'='*80}\n")
    
    holidays = []
    total_requests = 0
    total_records = 0
    day_count = 0
    total_days = (end_date - start_date).days + 1
    
    current_date = start_date
    while current_date <= end_date:
        day_count += 1
        date_str = current_date.strftime("%Y-%m-%d")
        weekday = current_date.strftime("%A")
        
        print(f"\n[{day_count}/{total_days}] [{date_str}] {weekday} - Processing...")
        
        # Get spot price from pre-downloaded data
        spot_price = spot_prices.get(date_str)
        
        if spot_price is None or spot_price == 0:
            print(f"  ⚠ No spot price available for {date_str} - marking as holiday")
            holidays.append(date_str)
            current_date += timedelta(days=1)
            continue
        
        print(f"  NIFTY Spot Price: {spot_price}")
        
        # Find expiry date (nearest expiry day)
        expiry_date = find_nearest_expiry_day(current_date, expiry_weekday)
        is_expiry_day = (current_date.weekday() == expiry_weekday)  # Check if today is expiry day
        
        # Calculate strikes
        strikes = calculate_strikes(spot_price, num_strikes=20)
        
        # Check if expiry day has data, if not try previous day
        expiry_date_iso = expiry_date.strftime("%Y-%m-%dT00:00:00.000Z")
        sample_strike = strikes[len(strikes)//2]  # Use middle strike as sample
        
        weekday_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        expiry_day_name = weekday_names[expiry_weekday]
        
        print(f"  Checking expiry date: {expiry_date.strftime('%d-%b-%Y').upper()} ({expiry_date.date()})...", end=" ")
        has_expiry_data = check_expiry_has_data(breeze, date_str, expiry_date_iso, sample_strike)
        total_requests += 1
        
        if not has_expiry_data:
            # Fallback to previous day expiry
            previous_day_expiry = find_previous_day(expiry_date, expiry_weekday)
            previous_day_expiry_iso = previous_day_expiry.strftime("%Y-%m-%dT00:00:00.000Z")
            prev_day_name = weekday_names[previous_day_expiry.weekday()]
            print(f"No data for {expiry_day_name} expiry, trying {prev_day_name} {previous_day_expiry.strftime('%d-%b-%Y').upper()}...", end=" ")
            has_previous_data = check_expiry_has_data(breeze, date_str, previous_day_expiry_iso, sample_strike)
            total_requests += 1
            
            if has_previous_data:
                expiry_date = previous_day_expiry
                expiry_date_iso = previous_day_expiry_iso
                print(f"✓ {prev_day_name} expiry has data")
            else:
                print(f"✗ No data for {prev_day_name} expiry either")
        else:
            print(f"✓ {expiry_day_name} expiry has data")
        
        expiry_date_str = expiry_date.strftime("%d-%b-%Y").upper()
        print(f"  Using Expiry Date: {expiry_date_str} ({expiry_date.date()})")
        
        # If it's expiry day, also prepare next expiry
        next_expiry_date = None
        next_expiry_date_iso = None
        if is_expiry_day:
            next_expiry_date = find_next_expiry_day(expiry_date, expiry_weekday)
            next_expiry_date_iso = next_expiry_date.strftime("%Y-%m-%dT00:00:00.000Z")
            next_expiry_date_str = next_expiry_date.strftime("%d-%b-%Y").upper()
            print(f"  Expiry Day Detected! Also downloading next expiry: {next_expiry_date_str} ({next_expiry_date.date()})")
        
        print(f"  Downloading {len(strikes)} strikes: {strikes[0]} to {strikes[-1]}")
        
        # Download data for each strike and right type (current expiry)
        day_data = defaultdict(lambda: defaultdict(list))
        day_data_count = 0
        
        for strike in strikes:
            for right_type in ['call', 'put']:
                print(f"    Downloading {right_type.upper()} {strike}...", end=" ")
                data = download_options_data(breeze, date_str, expiry_date_iso, strike, right_type)
                total_requests += 1
                
                if data:
                    day_data[right_type][str(strike)].extend(data)
                    day_data_count += len(data)
                    print(f"✓ {len(data)} records")
                else:
                    print("✗ No data")
                
                # Rate limiting - API allows 100 calls per minute
                # Pause every 50 requests to stay under 100/minute limit
                if total_requests % 50 == 0:
                    print(f"  Rate limit check: {total_requests} requests made, pausing 2 seconds...")
                    time.sleep(2)
        
        # If it's expiry day, also download next expiry data to separate file
        next_expiry_data = None
        next_expiry_data_count = 0
        next_expiry_date_used = None
        next_expiry_date_str_used = None
        
        if is_expiry_day and next_expiry_date_iso:
            # First check if next expiry has data
            print(f"\n  Checking next expiry data ({next_expiry_date.strftime('%d-%b-%Y').upper()})...", end=" ")
            has_next_expiry_data = check_expiry_has_data(breeze, date_str, next_expiry_date_iso, sample_strike)
            total_requests += 1
            
            if has_next_expiry_data:
                print("✓ Next expiry has data")
                next_expiry_date_used = next_expiry_date
                next_expiry_date_str_used = next_expiry_date.strftime("%d-%b-%Y").upper()
                next_expiry_date_iso_used = next_expiry_date_iso
            else:
                # Fallback to one day before the next expiry date
                print("✗ No data for next expiry")
                previous_day_of_next_expiry = next_expiry_date - timedelta(days=1)
                previous_day_expiry_iso = previous_day_of_next_expiry.strftime("%Y-%m-%dT00:00:00.000Z")
                previous_day_expiry_str = previous_day_of_next_expiry.strftime("%d-%b-%Y").upper()
                print(f"  Trying one day before next expiry: {previous_day_expiry_str} ({previous_day_of_next_expiry.date()})...", end=" ")
                has_previous_day_data = check_expiry_has_data(breeze, date_str, previous_day_expiry_iso, sample_strike)
                total_requests += 1
                
                if has_previous_day_data:
                    print("✓ Previous day of next expiry has data")
                    next_expiry_date_used = previous_day_of_next_expiry
                    next_expiry_date_str_used = previous_day_expiry_str
                    next_expiry_date_iso_used = previous_day_expiry_iso
                else:
                    print("✗ No data for previous day of next expiry either")
                    # Still try to download next expiry data even if check failed
                    # Sometimes the check might fail but actual download works
                    print("  Attempting to download next expiry data anyway...")
                    next_expiry_date_used = next_expiry_date
                    next_expiry_date_str_used = next_expiry_date.strftime("%d-%b-%Y").upper()
                    next_expiry_date_iso_used = next_expiry_date_iso
            
            # Download data for the selected expiry (next or previous)
            if next_expiry_date_used:
                print(f"\n  Downloading expiry data ({next_expiry_date_str_used})...")
                next_expiry_data = defaultdict(lambda: defaultdict(list))
                
                for strike in strikes:
                    for right_type in ['call', 'put']:
                        print(f"    Downloading {right_type.upper()} {strike} ({next_expiry_date_str_used})...", end=" ")
                        data = download_options_data(breeze, date_str, next_expiry_date_iso_used, strike, right_type)
                        total_requests += 1
                        
                        if data:
                            next_expiry_data[right_type][str(strike)].extend(data)
                            next_expiry_data_count += len(data)
                            print(f"✓ {len(data)} records")
                        else:
                            print("✗ No data")
                        
                        # Rate limiting
                        if total_requests % 50 == 0:
                            print(f"  Rate limit check: {total_requests} requests made, pausing 2 seconds...")
                            time.sleep(2)
        
        if day_data_count == 0:
            print(f"  ⚠ No data for this day - marking as holiday")
            holidays.append(date_str)
        else:
            print(f"  ✓ Total records for {date_str}: {day_data_count}")
            total_records += day_data_count
            
            # Save current expiry data to normal file
            output_file = save_daily_data(date_str, dict(day_data), spot_price, expiry_date_str)
            print(f"  ✓ Data saved to {output_file}")
            
            # If it's expiry day and we have next expiry data, save to separate file
            if is_expiry_day and next_expiry_data and next_expiry_data_count > 0:
                next_expiry_file = save_next_expiry_data(date_str, dict(next_expiry_data), spot_price, next_expiry_date_str_used)
                print(f"  ✓ Next expiry data saved to {next_expiry_file}")
                total_records += next_expiry_data_count
        
        current_date += timedelta(days=1)
    
    # Save summary
    print("\n" + "=" * 80)
    print("Download Summary")
    print("=" * 80)
    print(f"Total days processed: {day_count - len(holidays)}")
    print(f"Holidays detected: {len(holidays)}")
    if holidays:
        print(f"  Holiday dates: {', '.join(holidays)}")
    print(f"Total API requests: {total_requests}")
    print(f"Total records downloaded: {total_records}")
    print(f"\nFiles created:")
    print(f"  - nifty_options_YYYY-MM-DD.json (one file per trading day)")
    print(f"\nNote: Spot prices are read from nifty_spot_prices.json")

if __name__ == "__main__":
    main()
